import type { Metadata } from "next";
import "./globals.css";
import { Itim } from 'next/font/google';
import DynamicCursor from "./components/DynamicCursor";
const itim = Itim({
  subsets: ['latin'], 
  weight:  '400'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={itim.className}>
      <DynamicCursor />
        {children}
      </body>
    </html>
  );
}
