import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import DynamicCursor from "./components/DynamicCursor";
const poppins = Poppins({
  subsets: ['latin'], // Specify the character set
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Font weights to include
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <DynamicCursor />
        {children}
      </body>
    </html>
  );
}
